version: '3.4'

services:
  serversidenodeforgit:
    image: serversidenodeforgit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3005
