version: '3.4'

services:
app:
    build: ../server-side-nodeForGit/app
    ports:
      - "3006:3006"
    networks:
      - TimeOut-network
app1:
    build: ./app
    ports:
      - "3005:3005"
    networks:
      - TimeOut-network
serversidenodeforgit:
    image: serversidenodeforgit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3005:3005
networks:
  timeout_network:
    driver: bridge
